# The docker-compose.yml file is __only__ used for local development.
# This means that changes to this file will not affect cloud deployments in any way.
# Read more at https://docs.divio.com/reference/docker-docker-compose/
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    environment:
      DATABASE_URL: postgres://postgres:postgres@database_default:5432/db
    depends_on:
      database_default:
        condition: service_healthy
    # The following command is used to start the local development server.
    # Removing this line will mimic the deployment behaviour on Divio Cloud.
    command: python manage.py runserver 0.0.0.0:80

  database_default:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ".:/app:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 5s
      retries: 10
