version: "3"

services:
  web:
    build: "."
    ports:
      - "8000:80"
    command: python manage.py runserver 0.0.0.0:80
    environment:
      DATABASE_URL: postgres://postgres@database_default:5432/db
    volumes:
      - ".:/app:rw"
    links:
      - "database_default"

  database_default:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ".:/app:rw"
